Doc 960 gsql 101 changes
tigergraph/gsql-docs pull request #10
Opened 2021-12-18 07:59 UTC by a-m-thomas

2021-12-20 21:31 UTC, lennessyy commented
@a-m-thomas Hi Alex, I think something went wrong with this PR. If you look at the changed files, you'll see that there are a lot of unresolved conflicts.

Please resolve the conflicts or start a new branch with only the changes you made.

2021-12-20 21:34 UTC, lennessyy requested changes

2022-01-06 05:34 UTC, a-m-thomas commented on .github/workflows/main.yml
> +>>>>>>> b7e5ee06b72ef8e89652bf1fbac8cfee2e10aba7
Can this file simply be deleted?

2022-01-31 23:12 UTC, closed without merging

2022-01-31 23:13 UTC, lennessyy commented
closing because this one is too old