[DOC-2113] feat(optimizer): Histogram Stats API Update and Enhancement;
tigergraph/gsql-docs pull request #140
Opened 2024-06-26 17:10 UTC by romansod

Makes several fixes to existing documentation while also adding all of the new implicit parameterization with examples

2024-06-27 20:44 UTC, victorleeTG requested changes
A combination of
1) Statements that aren't clear enough.
2) Missing periods at ends of sentences (maybe run a spell checker?)
3) Style issues: avoid "we" when you mean the "the product"; capitalization of GSQL keywords; consistent verb tense; ...

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/pages/query-optimizer/stats-api.adoc
> +Buckets: Increasing the number of buckets will increase the granularity of the computed histogram, while decreasing the number of buckets will increase compaction. Choosing the right bucket count sho
```suggestion
**Buckets**: Increasing the number of buckets will increase the granularity of the computed histogram, while decreasing the number of buckets will increase compaction. Choosing the right bucket count should be done based on the use case first, then adjusted afterwards if necessary. Please see recommendations below for best practices.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/pages/query-optimizer/stats-api.adoc
> +NDV (Number of Distinct Values): this value is approximated for each bucket. For discrete datatypes (uint, int, datetime) this will represent the maximum potential NDV. For floating point, non discre
```suggestion
**NDV** (Number of Distinct Values): This value is approximated for each bucket. For discrete datatypes (UINT, INT, DATETIME) this will represent the maximum potential NDV. For floating point, non discrete datatypes (float, double), assuming uniform distribution means assuming all values in a bucket are distinct. Primary ID’s always have exact NDV values, since they are by definition all unique values.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/pages/query-optimizer/stats-api.adoc
> +NDV (Number of Distinct Values): this value is approximated for each bucket. For discrete datatypes (uint, int, datetime) this will represent the maximum potential NDV. For floating point, non discre
I don't follow your explanation of NDV for different data types. I get the concept that the system knows you have X values in bucket B, but it doesn't know if the values are distinct. So, at the extreme end, all the values are distinct. What I don't get is the distinction you are making about floating point values. "non discrete datatypes"  - in a computer, floating point values are actually discrete. Maybe you are trying to say that true value 0.999999 and true value 1.000001 might both be represented by 1.000000. But I think the bottom line is that the histogram assumes all values are distinct. Is that the case or not?

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +`GSQL-Thread-Limit` indicates the thread limit per histogram computation. In the case of multiple computations this thread limit will apply to each histogram computation individually
```suggestion
`GSQL-Timeout` indicates timeout for the request. In the case of multiple computations, this timeout covers the overall timeout, including all the histogram computations.
`GSQL-Thread-Limit` indicates the thread limit per histogram computation. In the case of multiple computations this thread limit will apply to each histogram computation individually.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +By default we use a bucket value of 256. With discrete datatypes, a bucket count that is lower than the specified target may be necessary depending on the data the histogram is computed over.
What do you mean by "specified target"? 
Did you mean "default value"?

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +In addition to individually requesting histogram computation through the POST endpoint, it is also possible to gather ALL histograms on a per schema object basis. `bucket` parameter can still be spec
```suggestion
In addition to requesting individual histograms through the POST endpoint, it is also possible to request all valid histograms on a per schema object basis.  The`bucket` parameter can still be specified and will be applied to every histogram being computed in the request.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +The output generated is in the same format as individual computation, with the `success` field tracking the total number of successful computations and `failure` will track all of the failures encoun
```suggestion
The output generated is in the same format as individual computation, with the `success` field tracking the total number of successful computations and `failure` tracking all of the failures encountered:
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +`READ_DATA` privilege is required to retrieve a histogram for a particular attribute. This can be at the attribute level or a higher level. Note that for edge based histograms, the 'from' and 'to' ve
```suggestion
`READ_DATA` privilege is required to retrieve a histogram for a particular attribute. This can be at the attribute level or a higher level. Note that for edge-based histograms, the 'from' and 'to' vertex are not read and therefore only the edge requires the privilege.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +If leader switch or some other interruption takes place in GSQL we will not be able to resume progress. Statistics are stored as they are computed along with their start and end timestamps so there i
```suggestion
If leader switch or some other interruption takes place in GSQL the histogram operation will not be able to resume. Statistics are stored as they are computed along with their start and end timestamps so there is no progress lost. See recommendations for some suggestions on how to handle such situations.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +1. If timeout or some other event interrupts the collection of all the desired statistics, specifying a smaller subset of histograms based on what still has yet to be gathered will reduce the amount
```suggestion
1. If timeout or some other event interrupts the collection of all the desired statistics, specifying a smaller subset of histograms based on what still has yet to be gathered will reduce the amount of regathering.
For example, if executing a histogram computation request for attributes under all graphs, and after 2/4 graphs are fully gathered a timeout occurs, you can issue two requests at the graph level for graphs 3 and 4.
```

2024-06-27 20:44 UTC, victorleeTG commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +3. When choosing the right bucket value, the first step is to determine the requirements of the use case. Then, consider the granularity and compaction desired based on accuracy and performance / sto
```suggestion
2. When possible, it is best to schedule histogram computations after schema change jobs and data loading, not before. This is to ensure the statistics best reflect the current state of the database.

3. When choosing the right bucket value, the first step is to determine the requirements of the use case. Then, choose the fewer number of buckets that provides enough granularity.
```

2024-06-28 02:50 UTC, romansod commented on modules/gsql-v2/querying/pages/query-optimizer/stats-api.adoc
> +NDV (Number of Distinct Values): this value is approximated for each bucket. For discrete datatypes (uint, int, datetime) this will represent the maximum potential NDV. For floating point, non discre
I see your point. Your understanding of my intention is correct. Maybe it is easier if I refer to integral vs floating point?

The distinction here is as follows:

1. Primary_ID regardless of data type will always have exact ndv
2. Integral (uint, int, datetime) approximate ndv with a max ndv (ie the actual ndv may be lower but never higher)
3. Floating point (float, double) approximate ndv by assuming all values are distinct

2024-06-28 02:54 UTC, romansod commented on modules/gsql-v2/querying/partials/histogram-api.adoc
> +By default we use a bucket value of 256. With discrete datatypes, a bucket count that is lower than the specified target may be necessary depending on the data the histogram is computed over.
By specified target, I am trying to explain how, if we are using say an integer data type with the following values:
```
0, 1, 2, 3
```
If the user suggests a target bucket number of say 10, we will instead use 4. So the user specified target bucket count is a target bucket count, but we may reduce that if it is simply not compatible to the maximum, sensible bucket number (in the example, 4)

2024-07-02 14:20 UTC, victorleeTG commented on modules/gsql-v2/querying/pages/query-optimizer/stats-api.adoc
> +NDV (Number of Distinct Values): this value is approximated for each bucket. For discrete datatypes (uint, int, datetime) this will represent the maximum potential NDV. For floating point, non discre
sounds good

2024-07-02 15:14 UTC, victorleeTG approved these changes

2024-07-02 15:14 UTC, merged