[DOC-2105] fix(gsql): add warnings for blocked to_vertex and to_vertex_set usage in ACCUM and POST-ACCUM;
tigergraph/gsql-docs pull request #155
Opened 2024-07-22 21:22 UTC by jue-yuan

[DOC-2105](https://graphsql.atlassian.net/browse/DOC-2105)
Add warnings for blocked to_vertex and to_vertex_set usage in ACCUM and POST-ACCUM

[DOC-2105]: https://graphsql.atlassian.net/browse/DOC-2105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-08 07:25 UTC, YipingXiongTG approved these changes

2024-08-27 00:52 UTC, arun-TG-PM commented on modules/querying/pages/func/vertex-methods.adoc
> +Since 4.1.0, we cannot use `to_vertex()` in ACCUM or POST-ACCUM clauses any more. An error message will be prompted when we try to do so.
@jue-yuan - Please include an example of an error message if possible.

2024-08-27 00:52 UTC, arun-TG-PM approved these changes

2024-08-28 11:10 UTC, victorleeTG requested changes

2024-08-28 11:10 UTC, victorleeTG commented on modules/querying/pages/func/vertex-methods.adoc
> +Since 4.1.0, we cannot use `to_vertex_set()` in ACCUM or POST-ACCUM clauses any more. An error message will be prompted when we try to do so.
```suggestion
Since v4.1.0, `to_vertex_set()` may not be used in ACCUM or POST-ACCUM clauses.
```
There is no "we" in the GSQL reference manual.

2024-08-28 11:10 UTC, victorleeTG commented on modules/querying/pages/func/vertex-methods.adoc
> +Since 4.1.0, we cannot use `to_vertex()` in ACCUM or POST-ACCUM clauses any more. An error message will be prompted when we try to do so.
```suggestion
Since v4.1.0, `to_vertex()` may not be used in ACCUM or POST-ACCUM clauses.
```

2024-08-28 11:11 UTC, merged