Doc 1425 optimizer ga
tigergraph/gsql-docs pull request #80
Opened 2022-11-09 03:54 UTC by lennessyy

2022-11-09 16:56 UTC, joshua-tg-19 requested changes

2022-11-09 16:56 UTC, joshua-tg-19 commented on modules/querying/pages/query-optimizer/enable-cost-optimizer.adoc
> -A _refined edge type_ means an edge type with a specified pair of `from` and `to` vertex types as well as their reverse edge types if they exist.
We haven't completely integrated automatic cardinality stats collection, so this API still exists.

2022-11-09 16:56 UTC, joshua-tg-19 commented on modules/querying/partials/histogram-api.adoc
> +-d '{"graph":"ldbc_snb", "edge":"LIKES", "from":"Person", "to":"Comment", "attribute":"creationDate", "buckets":10, "histogram": [{"ndv":1,"upperBound":"2010-05-10 22:30:29","rowsUpper":1,"rowsTotal"
This is an internal API only, so we don't want to publicly document it.

2022-11-09 19:16 UTC, joshua-tg-19 approved these changes

2022-11-09 19:16 UTC, joshua-tg-19 commented on modules/querying/pages/query-optimizer/stats-api.adoc
> +The endpoints on this page calculate histogram statistics for a vertex or refined edge type.
nit: I think you meant to revert this change.

2022-11-10 19:26 UTC, alexthomasTG approved these changes

2022-11-10 23:12 UTC, merged